-- cheatsheet.lua — floating window with custom keybindings
-- open with :Cheatsheet or <leader>?

local lines = {
  "  Custom Keybindings                                          ",
  " ─────────────────────────────────────────────────────────── ",
  "  NAVIGATION                                                  ",
  "   H / L            prev / next buffer                        ",
  "   <BS>             quit window (save first if already on disk)",
  "                     -- file bufs only; opens netrw if last win ",
  "   <C-d> / <C-u>   scroll ½ page, cursor stays centred        ",
  "   n / N            next / prev search result (centred)       ",
  " ─────────────────────────────────────────────────────────── ",
  "  FILES & BUFFERS                                             ",
  "   <leader>pv       open file explorer (netrw)                ",
  "   <leader>a        toggle file structure sidebar (aerial)    ",
  "   gx               open URL under cursor in browser          ",
  "   <leader>gf       open path under cursor in new nvim win    ",
  "   <leader>yl       copy path:line (visual: path:start-end)   ",
  " ─────────────────────────────────────────────────────────── ",
  "  NETRW                                                       ",
  "   <CR>             dir: descend  /  file: open in new tab    ",
  "   <BS>             go up a directory (overrides quit/scroll) ",
  "   o                open file in current window               ",
  "   i                toggle tree / plain listing              ",
  "   T  (or <S-CR>)   open file in new tab + lcd to its dir     ",
  "   yp               copy file path to Windows clipboard       ",
  "   !                run shell cmd; % = file under cursor      ",
  "   %                create new file                           ",
  "   d                create new directory                      ",
  "   R                rename file/dir under cursor              ",
  "   mf               mark file/dir (repeat to mark more)       ",
  "   mt               set target: go to dest dir first, press mt",
  "   mm               move marks to target (mf + mm: same buf,  ",
  "                    i.e. mark AFTER navigating back to source)",
  "   mc               copy marked file(s) to target dir         ",
  "   mu               unmark all                                ",
  "   g?               netrw quick help (moved off <F1>)         ",
  " ─────────────────────────────────────────────────────────── ",
  "  nv  (from the shell: nv <pattern> — see nv --help)          ",
  "   nv api           opens nvim at once, searches in the       ",
  "                    background; best 10 hits become tabs you  ",
  "                    are NOT dragged into, all hits are listed ",
  "   <CR> (in list)   open that path in a tab next to this one  ",
  "                    (a directory opens as netrw); gf works too",
  "   R / q            search again / close the list             ",
  "   nvf api          = nv -f -t: just open the best hit here   ",
  "   f api            the same search, printed in the shell     ",
  " ─────────────────────────────────────────────────────────── ",
  "  TELESCOPE                                                   ",
  "   <C-o>            find files (vim cwd — stable)             ",
  "   <leader>fg       live grep   (vim cwd — stable)            ",
  "   <leader>O        lcd to ctx dir + find files               ",
  "   <leader>fG       lcd to ctx dir + live grep                ",
  "   <leader>fo       recent files                              ",
  "   <leader>fb       open buffers                              ",
  "   <Tab> (in list)  mark item, move to next                   ",
  "   <C-q> (in list)  send marked items to quickfix list        ",
  " ─────────────────────────────────────────────────────────── ",
  "  HARPOON                                                     ",
  "   <leader>g        add current file                          ",
  "   <C-g>            quick menu                                ",
  "   <C-1> … <C-9>   jump to harpoon slot 1–9                   ",
  " ─────────────────────────────────────────────────────────── ",
  "  EDITING                                                     ",
  "   J / K  (visual)  move selection down / up                  ",
  "   J / K  (normal)  page down / up (= <PageDown>/<PageUp>)    ",
  "   <leader>j        join line below (cursor stays in place)   ",
  "   <leader>k        join onto line above (cursor stays)       ",
  "   <leader>p        paste without overwriting buffer          ",
  "   <leader>D        delete without overwriting buffer         ",
  "   <leader>Y        yank to system clipboard                  ",
  "   <leader>P        paste from system clipboard               ",
  "   <leader>s        search-replace word under cursor          ",
  "   <C-p> / :Yanks   yank history as a buffer (split below);   ",
  "                    :Yanks! for a vsplit on the right         ",
  "     <CR> paste it where you came from, close   p / P  same   ",
  "     d    delete from the history   R  refresh   q  close     ",
  "   ONE history (last 15), shared live by every running nvim   ",
  "   :FixLineEndings  strip ^M, set fileformat=unix             ",
  " ─────────────────────────────────────────────────────────── ",
  "  GIT REVIEW                                                  ",
  "   :GitReview       the branch as one markdown buffer:        ",
  "                    uncommitted changes, then the whole       ",
  "                    branch as one net diff, then every        ",
  "                    commit with its message and file diffs    ",
  "                    no arg = since the fork from main;        ",
  "                    :GitReview 10 / <base-ref> / a..b         ",
  "                    :GitReview! opens a vsplit, not a tab     ",
  "     <CR>  open the file at that diff line   R  refresh       ",
  "     ]] / [[  next / previous commit   q  close               ",
  "     zM  fold to one line per commit   zR  unfold             ",
  " ─────────────────────────────────────────────────────────── ",
  "  LSP  (Python/Zig — run :LspEnable or <leader>le first)      ",
  "   gd               go to definition                          ",
  "   gi               hover docs (press again to focus float,   ",
  "                    then <CR> on a link to jump to it)        ",
  "   ]d / [d          next / prev diagnostic                    ",
  "   gn / gp          next / prev diagnostic (alt. keys)        ",
  "   ge               expand diagnostic under cursor            ",
  "   <leader>K        all diagnostics in location list          ",
  "   grn              rename symbol   (nvim 0.11 default)       ",
  "   gra              code action     (nvim 0.11 default)       ",
  "   grr              references      (nvim 0.11 default)       ",
  "   gri              implementation  (nvim 0.11 default)       ",
  " ─────────────────────────────────────────────────────────── ",
  "  AI COMPLETION  (Copilot, off by default)                    ",
  "   <leader>la          enable Copilot, project-wide           ",
  "                    (writes/trusts/sources .nvim.lua)         ",
  "   :Copilot auth    sign in (one-time; opens URL + code)      ",
  "   :Copilot status  confirm signed in                         ",
  "   <A-]> / <A-[>    request / cycle suggestion                ",
  "   <A-a>            accept full suggestion                    ",
  "   <A-l>            accept one line of suggestion             ",
  "   <A-e>            dismiss suggestion                        ",
  "   <Right>          accept suggestion (else: cursor right)    ",
  "   <S-Right>        request/cycle suggestion                  ",
  "   config files (add a language / see what's supported):      ",
  "     LSP (Python, Zig)    -> after/plugin/lsp.lua             ",
  "     formatter (Zig, md)  -> after/plugin/conform.lua         ",
  "     treesitter parsers   -> lua/shared/lazy.lua              ",
  "     AI completion has no per-language list — once opted      ",
  "     in, it applies to every filetype (Zig included).         ",
  " ─────────────────────────────────────────────────────────── ",
  "  AI REFACTOR  (Copilot Chat)                                 ",
  "   (visual) <leader>lr   describe a refactor for selection    ",
  "                    -> :CopilotChat <description> <CR>        ",
  "   in the reply split:                                        ",
  "     <C-y>   apply diff over your selection                   ",
  "     gd      show diff again    gy   yank diff                ",
  "     q       close without applying                           ",
  "   also: :CopilotChatFix/Optimize/Docs/Tests/Explain/         ",
  "         Review/Commit (canned prompts, no selection needed)  ",
  " ─────────────────────────────────────────────────────────── ",
  "  TABS  (<C-f> chord — <C-t>/<C-b> belong to the terminal)    ",
  "   <PageUp>         previous tab (left in the tabline)        ",
  "   <PageDown>       next tab     (right in the tabline)       ",
  "                    J / K still page; <PageUp> no longer does ",
  "   <C-f>n           new empty tab                             ",
  "   <C-f>x           close this tab                            ",
  "   <C-f>o           close all tabs but this one (\"only\")      ",
  "   <C-f>b           pick a tab (telescope)                    ",
  "   <C-f>s           hsplit: orig buf bottom, prev-tab top     ",
  "   <C-f>v           vsplit: orig buf left,   prev-tab right   ",
  "   <C-f>m           move this split into its own tab (<C-w>T) ",
  "   <C-f>< / <C-f>> move this tab left / right                 ",
  "   gt / gT          previous / next tab (reversed from stock) ",
  " ─────────────────────────────────────────────────────────── ",
  "  TERMINAL   (terminals run tmux — see tmux_cheatsheet)       ",
  "   <C-t>t           new Windows Terminal window (detached)    ",
  "   <C-t>T           new terminal in a vsplit (side), runs tmux",
  "   <C-s>            new terminal in an hsplit (below), tmux   ",
  "  in a terminal (forwarded to tmux; prefix is C-b):           ",
  "   <C-s>            tmux: split pane (side by side)           ",
  "   <C-n>            tmux: new window                          ",
  "   <C-h> / <C-l>    tmux: previous / next window (see bar)    ",
  "   <C-\\> / <C-]>   tmux: move window left / right (wraps)    ",
  "   <A-h/j/k/l>      tmux: move between panes                  ",
  "   <C-k> / <C-j>    scroll pane up / down (sends mouse wheel) ",
  "   <C-q>            tmux: close pane — the last pane of an    ",
  "                    nvim split closes the split itself, so    ",
  "                    an accidental split is undone by <C-q>    ",
  "   <C-t>            fork: new WT window at this pane's cwd     ",
  "   <C-w>            leave terminal mode -> terminal-NORMAL;    ",
  "                    <C-w>h etc. from there, i resumes TERMINAL ",
  "   <C-p>            yank history -> <CR> pastes into the shell",
  "   <C-e>            scrollback: full pane history as a big     ",
  "                    split above a thin terminal strip — edit, ",
  "                    /, visual, yank, paste down into the shell",
  "                    i or <C-e> close it; <C-e> again refreshes",
  "                    <C-i> = insert mode in the scrollback     ",
  "   C-b w            tmux: window list   C-b hjkl  panes       ",
  "   C-b d            tmux: detach        C-b [     copy/scroll ",
  " ─────────────────────────────────────────────────────────── ",
  "  INTERACTIVE MODE  (notebook-style /instructions in a buffer)",
  "   :InteractiveMode  enable for current buffer                ",
  "   /cmd args         write + leave the line to run it         ",
  "   /cmd \"a''         multi-line string arg (see '' marker)   ",
  "     b\"''                                                    ",
  "   # /cmd             comment out a running instr. to kill it ",
  "   <leader>ii          on a running instr: jump to its live   ",
  "                    terminal (e.g. drive lazygit directly)    ",
  "   <C-e>            (in that terminal) exit terminal mode     ",
  "   <leader>ii        (in that terminal) jump back to notebook ",
  " ─────────────────────────────────────────────────────────── ",
  "  CLICKUP                                                     ",
  "   :ClickupTodosRun  run /instructions in buffer, in place    ",
  "                    (no temp file — stdin/stdout round trip)  ",
  " ─────────────────────────────────────────────────────────── ",
  "  MARKDOWN EDITING  (ported from the Obsidian vimrc)          ",
  "   n = word under cursor, v = selection; repeat to undo       ",
  "   ~                ~~strikethrough~~  (was: toggle case)     ",
  "   `                `code inline`      (was: mark jump `a)    ",
  '   "                "quoted"           (was: register pfx)    ',
  "   '                'quoted'           (was: mark jump 'a)    ",
  '   <leader>q        "quoted"  (leader alias for ")            ',
  "   gb               toggle a bullet list on line/selection    ",
  "                    (was: Comment.nvim gb/gbc; <leader>C      ",
  "                     still block comments a selection)        ",
  "   markdown/text buffers only:                                ",
  "    <leader>c       `code inline`  (else: line comment)       ",
  "    <leader>l       [text](url) + insert mode in the parens   ",
  "                    (so <leader>la/lr/le — Copilot, Copilot   ",
  "                     Chat, LspEnable — are out of reach here) ",
  "   no mark-jump key is left (both ` and ' are taken);         ",
  "   registers: <leader>Y/P system, <leader>p/D black-hole      ",
  " ─────────────────────────────────────────────────────────── ",
  "  MARKDOWN TABLES  (ported from the Obsidian tables plugin)   ",
  "   type `| name | age |` then <CR> or <Tab> — the             ",
  "   | --- | --- | row is written and it becomes a table        ",
  "   <Tab>            next cell; at the last one, a new column  ",
  "   <S-Tab>          previous cell (hops the | --- | row)      ",
  "   <CR>             next row, created if there is none;       ",
  "                    on an empty last row, leave the table     ",
  "   <A-h> / <A-l>    insert a column left / right              ",
  "   <A-k> / <A-j>    insert a row above / below                ",
  "   <A-S-h/l>        move the column left / right              ",
  "   <A-S-k/j>        move the row up / down                    ",
  "   <A-d>            delete the column under the cursor        ",
  "   <A-a>            cycle alignment none/left/center/right    ",
  "   <A-t>            insert a fresh 2x2 table here             ",
  "   :TableFormat     reflow (also happens on InsertLeave)      ",
  " ─────────────────────────────────────────────────────────── ",
  "  EXCALIDRAW                                                  ",
  "   :ExcalidrawRender  render this buffer's ```mermaid blocks  ",
  "                      into the local editor, stacked top-down ",
  "   :ExportToExcalidraw  the whole document on one canvas —    ",
  "                      prose, lists, tables, highlighted code, ",
  "                      images and diagrams, in a column        ",
  "                      (look: excalidraw-style.json)           ",
  "   :ExportToExcalidraw!  bang = scratch file in the cache dir ",
  "                      (shell: exo / exapp / exapp-render-doc) ",
  " ─────────────────────────────────────────────────────────── ",
  "  MARKDOWN EXPORT (mdpdf)                                     ",
  "   :ConvertToPdf     export buffer → .pdf beside the file     ",
  "   :ConvertToTex     export buffer → standalone .tex          ",
  "   :ConvertToWord    export buffer → .docx                    ",
  "   :ConvertTo… <sty>  word (default) | academic — <Tab> lists ",
  "   :ConvertTo…!      bang = discard cached build artifacts    ",
  "   :ConvertOpenBuildDir  open the /tmp artifact dir           ",
  "   /comment <text>   line comment, dropped from the export    ",
  "   /ignore …         drop a region; unclosed = rest of file   ",
  "   /endignore        close the region (optional)              ",
  "   /title <text>     document title, not a heading (optional) ",
  "   /tableofcontents  in-place contents list, no heading       ",
  "   /toc              short alias for /tableofcontents         ",
  "   /newpage          start a new page (alias /pagebreak)      ",
  "   /newline          one blank line (alias /blankline)        ",
  "   ## H {.notoc}     keep this section out of the contents    ",
  "   ```mermaid        fenced mermaid blocks render as diagrams ",
  "   ```js #id path.js  code: language, jump id, heading        ",
  "                      js/ts/sh/ps1/cs/yml aliases work        ",
  "   .nolinenumbers    one block without line numbers           ",
  "   [x](#my-heading)  jump link — slug, or the name as written ",
  "   ## H {#custom-id} explicit anchor on a heading             ",
  "   {#the-spot}       anchor on its own line (not a heading)   ",
  " ─────────────────────────────────────────────────────────── ",
  "  AUTOSAVE                                                    ",
  "   :AutoSaveToggle   on/off (on by default)                   ",
  "   :AutoSaveStatus   report current state                     ",
  "                    saves only buffers whose file exists      ",
  " ─────────────────────────────────────────────────────────── ",
  "  FOLDING                                                     ",
  "   zM / zR          fold all / unfold all                     ",
  "   zc / zo          close / open fold under cursor            ",
  "   zC / zO          close / open folds recursively            ",
  "   zL               level N / term / Enter=1 — global         ",
  "   zl               level N / term / Enter=1 — cursor         ",
  " ─────────────────────────────────────────────────────────── ",
  "  FINDING MORE                                                ",
  "   :help index       full list of built-in normal bindings    ",
  "   :help motion      movement commands                        ",
  "   :help operator    operators (d, c, y, …)                   ",
  "   :map              all active custom mappings (current buf) ",
  "   :nmap / :vmap     normal / visual custom mappings          ",
  "   q  (this window)  close cheatsheet                         ",
  " ─────────────────────────────────────────────────────────── ",
}

local function open_cheatsheet()
  -- dimensions
  local width  = 62
  local height = #lines

  local row = math.floor((vim.o.lines   - height) / 2)
  local col = math.floor((vim.o.columns - width)  / 2)

  -- scratch buffer
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.bo[buf].modifiable = false
  vim.bo[buf].filetype   = "cheatsheet"

  -- highlight groups (soft, no colour dependency)
  vim.api.nvim_buf_add_highlight(buf, -1, "Title",   0, 0, -1)  -- header
  for i, line in ipairs(lines) do
    if line:match("^%s*─") then
      vim.api.nvim_buf_add_highlight(buf, -1, "Comment", i - 1, 0, -1)
    elseif line:match("^%s+[A-Z %/&]+%s*$") then
      vim.api.nvim_buf_add_highlight(buf, -1, "Statement", i - 1, 0, -1)
    end
  end

  -- floating window
  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width    = width,
    height   = height,
    row      = row,
    col      = col,
    style    = "minimal",
    border   = "rounded",
    title    = " cheatsheet ",
    title_pos = "center",
  })

  vim.wo[win].cursorline = false
  vim.wo[win].wrap       = false

  -- close with q or <Esc>
  for _, key in ipairs({ "q", "<Esc>" }) do
    vim.keymap.set("n", key, function() vim.api.nvim_win_close(win, true) end, {
      buffer = buf, nowait = true, silent = true,
    })
  end
end

vim.api.nvim_create_user_command("Cheatsheet", open_cheatsheet, {
  desc = "Show custom keybindings cheatsheet",
})

vim.keymap.set("n", "<leader>?", open_cheatsheet, { desc = "Cheatsheet: custom keybindings" })
